name: Detection Rules CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  # Auto-create PR when pushing to feature branches
  create-pr:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    name: Auto-create Pull Request

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        EXISTING_PR=$(gh pr list --repo "${{ github.repository }}" --head "${BRANCH_NAME}" --base main --json number --jq '.[0].number')

        if [ -z "${EXISTING_PR}" ]; then
          gh pr create --repo "${{ github.repository }}" --base main --head "${BRANCH_NAME}" --title "Detection Rule: ${BRANCH_NAME}" --body "Detection rule update from ${BRANCH_NAME}"
          echo "Pull request created"
        else
          echo "Pull request already exists"
        fi

  # Validate rules on PR
  validate:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Validate Detection Rules

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install detection-rules dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install lib/kibana
        pip install lib/kql

    - name: Validate custom rules
      run: |
        if [ -d "custom-rules/rules" ] && ls custom-rules/rules/*.toml > /dev/null 2>&1; then
          for rule in custom-rules/rules/*.toml; do
            python -m detection_rules test "$rule" || true
          done
        fi

  # Deploy to ec-dev when PR is merged to main
  deploy-to-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy Detection Rules to ec-dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install detection-rules dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install lib/kibana
        pip install lib/kql

    - name: Deploy to Development Kibana
      env:
        ELASTIC_CLOUD_ID: ${{ secrets.DEV_ELASTIC_CLOUD_ID }}
        ELASTIC_API_KEY: ${{ secrets.DEV_ELASTIC_API_KEY }}
      run: |
        mkdir -p custom-rules/rules
        if ls custom-rules/rules/*.toml > /dev/null 2>&1; then
          python -m detection_rules kibana --cloud-id="${ELASTIC_CLOUD_ID}" --api-key="${ELASTIC_API_KEY}" --space default import-rules -d custom-rules/rules/ || true
        fi
